CREATE TABLE TASK_RECOURCE 
(
  TASKRECOURCE_PK NUMBER NOT NULL 
, TASK_FK NUMBER NOT NULL 
, RESOURCE_FK VARCHAR2(40 BYTE) NOT NULL 
, TASKSTATUS NUMBER NOT NULL 
, ASSIGNED_DATE DATE 
, FINISHDATE DATE 
, CONSTRAINT TASKRECOURCE_PK PRIMARY KEY 
  (
    TASKRECOURCE_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE TASK 
(
  TASK_PK NUMBER(9, 0) NOT NULL 
, REQUEST_BY VARCHAR2(120 BYTE) 
, TASK_NAME VARCHAR2(250 BYTE) 
, TASK_DATE DATE 
, TASK_DUE_DATE DATE 
, TASK_TYPE NUMBER(2, 0) 
, TASK_SHORT_DESC VARCHAR2(250 BYTE) 
, REQUESTER_DEPT_ID VARCHAR2(10 BYTE) 
, SPONSOR_NAME VARCHAR2(250 BYTE) 
, SPONSOR_MOBILE VARCHAR2(15 BYTE) 
, SPONSOR_MAIL VARCHAR2(120 BYTE) 
, SPONSOR_PHONE VARCHAR2(20 BYTE) 
, REQUEST_TO VARCHAR2(120 BYTE) 
, TASK_START_DATE DATE 
, TASK_END_DATE DATE 
, TASK_REVIEWER VARCHAR2(120 BYTE) 
, TASK_NOTE VARCHAR2(250 BYTE) 
, FOLLOW_UP_NOTE VARCHAR2(250 BYTE) 
, ASSIGN_NOTE VARCHAR2(250 BYTE) 
, RESPONSABLIES VARCHAR2(250 BYTE) 
, ESTIMATION_IN_DAYS NUMBER(4, 0) 
, PENDINGISSUE VARCHAR2(250 BYTE) 
, REQUIREMENTTYPE NUMBER 
, PRIORITY NUMBER 
, PROJECT_FK NUMBER 
, SUB_TASK_FK NUMBER 
, CONSTRAINT TASK_PK PRIMARY KEY 
  (
    TASK_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE PS_TXN 
(
  ID NUMBER(20, 0) NOT NULL 
, PARENTID NUMBER(20, 0) 
, COLLID NUMBER(10, 0) NOT NULL 
, CONTENT BLOB 
, CREATION_DATE DATE DEFAULT sysdate 
, CONSTRAINT PS_TXN_PK PRIMARY KEY 
  (
    COLLID 
  , ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
) 
LOB (CONTENT) STORE AS SYS_LOB0000304970C00004$$ 
( 
  ENABLE STORAGE IN ROW 
  CHUNK 8192 
  RETENTION 
  CACHE 
  LOGGING 
  TABLESPACE "USERS" 
  STORAGE 
  ( 
    INITIAL 65536 
    NEXT 1048576 
    MINEXTENTS 1 
    MAXEXTENTS 2147483645 
    BUFFER_POOL DEFAULT 
  )  
);

CREATE TABLE PROJECT 
(
  PRJ_PK NUMBER NOT NULL 
, PRJ_NAME VARCHAR2(250 BYTE) 
, PRJ_DEPT_REQUESTER NUMBER(6, 0) 
, PRJ_DEPT_IMPLEMENT NUMBER(9, 0) NOT NULL 
, ACTUAL_START_DATE DATE 
, END_DATE_PANNED DATE 
, PRJ_STS_TIME NUMBER(1, 0) 
, SPONSOR_NAME VARCHAR2(200 BYTE) 
, SPONSOR_MOBILE VARCHAR2(15 BYTE) 
, SPONSOR_MAIL VARCHAR2(200 BYTE) 
, SPONSOR_PHONE VARCHAR2(15 BYTE) 
, PROJECT_STATUS NUMBER 
, PROJECTMANAGER NUMBER 
, PROJECT_TYPE NUMBER 
, CONSTRAINT PROJECT_PK PRIMARY KEY 
  (
    PRJ_PK 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOOKUP_M 
(
  LOOKUP_ID NUMBER(4, 0) NOT NULL 
, LOOKUP_NAME VARCHAR2(250 BYTE) 
, LOOKUP_NAME_EN VARCHAR2(250 BYTE) 
, LOKKUP_DESC VARCHAR2(250 BYTE) 
, ACTIVE_FLAG NUMBER(1, 0) 
, CONSTRAINT LOOKUP_M_PK PRIMARY KEY 
  (
    LOOKUP_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE LOOKUP_D 
(
  LOOKUP_D_ID NUMBER(3, 0) NOT NULL 
, LOOKUP_D_NAME VARCHAR2(250 BYTE) 
, LOOKUP_D_NAME_EN VARCHAR2(250 BYTE) 
, LOOKUP_D_VALUE NUMBER(3, 0) 
, ACTIVE_FLAG NUMBER(1, 0) 
, LOOKUP_ID NUMBER(4, 0) 
, CONSTRAINT LOOKUP_D_PK PRIMARY KEY 
  (
    LOOKUP_D_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

CREATE TABLE BPM_RESOURCE 
(
  RESOURCE_ID VARCHAR2(40 BYTE) NOT NULL 
, RESOURCE_NAME VARCHAR2(250 BYTE) 
, JOB_TITLE VARCHAR2(250 BYTE) 
, RESOURCE_MOBILE VARCHAR2(20 BYTE) 
, RESOURCE_MAIL_ADD VARCHAR2(150 BYTE) 
, ACTIVE_FLAG NUMBER(1, 0) 
, TEAM_LEADER NUMBER(1, 0) 
, REVIEW NUMBER(1, 0) 
, TEAM_MEMBER NUMBER(1, 0) DEFAULT 1 
, RESOURCE_TYPE NUMBER 
, DEPARTMENT NUMBER 
, TEAM_NAME_AR VARCHAR2(100 BYTE) 
, TEAM_NAME_EN VARCHAR2(100 BYTE) 
, CONSTRAINT BPM_RESOURCE_PK PRIMARY KEY 
  (
    RESOURCE_ID 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE "USERS" 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS 2147483645 
  BUFFER_POOL DEFAULT 
);

ALTER TABLE TASK_RECOURCE
ADD CONSTRAINT TASK_RECOURCE_BPM_RESOURC_FK1 FOREIGN KEY
(
  RESOURCE_FK 
)
REFERENCES BPM_RESOURCE
(
  RESOURCE_ID 
)
ENABLE;

ALTER TABLE TASK_RECOURCE
ADD CONSTRAINT TASK_RECOURCE_TASK_FK1 FOREIGN KEY
(
  TASK_FK 
)
REFERENCES TASK
(
  TASK_PK 
)
ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_PROJECT_FK1 FOREIGN KEY
(
  PROJECT_FK 
)
REFERENCES PROJECT
(
  PRJ_PK 
)
ENABLE;

ALTER TABLE TASK
ADD CONSTRAINT TASK_TASK_FK1 FOREIGN KEY
(
  SUB_TASK_FK 
)
REFERENCES TASK
(
  TASK_PK 
)
ENABLE;

ALTER TABLE LOOKUP_D
ADD CONSTRAINT LOOKUP_D_R01 FOREIGN KEY
(
  LOOKUP_ID 
)
REFERENCES LOOKUP_M
(
  LOOKUP_ID 
)
ENABLE;
