package sa.momra.applicationModule.Vo;

import java.sql.ResultSet;

import java.util.ArrayList;

import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.server.ViewRowImpl;
import oracle.jbo.server.ViewRowSetImpl;

import sa.momra.applicationModule.bean.UsersBean;
import sa.momra.applicationModule.bean.WlUsers;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 28 14:19:36 AST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class UsersWLImpl
  extends ViewObjectImpl
{
  /**
   * This is the default constructor (do not remove).
   */
  private ArrayList<UsersBean> usersList = new ArrayList<UsersBean>();

  public UsersWLImpl()
  {
  }

  /**
   * executeQueryForCollection - overridden for custom java data source support.
   */
  protected void executeQueryForCollection(Object qc, Object[] params, int noUserParams)
  {
    WlUsers.users();
    setFetchPosition(qc, 0);
    super.executeQueryForCollection(qc, params, noUserParams);
  }

  private void setFetchPosition(Object rowset, int position)
  {
    if (position == usersList.size() - 1)
    {
      setFetchCompleteForCollection(rowset, true);
    }
    setUserDataForCollection(rowset, new Integer(position));

  }

  private int getFetchPosition(Object rowset)
  {
    int value = ((Integer) getUserDataForCollection(rowset)).intValue();
    return value;
  }

  /**
   * hasNextForCollection - overridden for custom java data source support.
   */
  protected boolean hasNextForCollection(Object qc)
  {
    return getFetchPosition(qc) < usersList.size();
  }

  /**
   * createRowFromResultSet - overridden for custom java data source support.
   */
  protected ViewRowImpl createRowFromResultSet(Object qc, ResultSet resultSet)
  {
    int fetchPosition = getFetchPosition(qc);
    ViewRowImpl newRow = (ViewRowImpl) createNewRowForCollection(qc);
    newRow.setAttribute("UserName", WlUsers.users().get(fetchPosition));
    newRow.setAttribute("UserDiscretion", WlUsers.usersDesc.get(fetchPosition));
    setFetchPosition(qc, fetchPosition + 1);
    return newRow;
  }

  /**
   * getQueryHitCount - overridden for custom java data source support.
   */
  public long getQueryHitCount(ViewRowSetImpl viewRowSet)
  {
    long value = super.getQueryHitCount(viewRowSet);
    return value;
  }
}
